server:
  port: 8080

spring:
  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-db

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database: h2

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.type.descriptor.sql: trace